### ISSUE TITLE
How to reuse IntegerParameterType

### ISSUE THREAD

**Issue by yashi** [yamcs/pymdb#1]
How can I reuse an `IntegerParameterType`?

**This is what I want to generate**

Note that `uptime_type` is used for both `uptime` and `uptime2`.

```xml
<?xml version="1.0" ?>
<!--
This file was automatically generated with Yamcs PyMDB.
See https://github.com/yamcs/pymdb
-->
<SpaceSystem xmlns="http://www.omg.org/spec/XTCE/20180204" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.omg.org/spec/XTCE/20180204 https://www.omg.org/spec/XTCE/20180204/SpaceSystem.xsd" name="Spacecraft">
  <TelemetryMetaData>
    <ParameterTypeSet>
      <IntegerParameterType name="telemetry-type" signed="false" sizeInBits="32">
        <IntegerDataEncoding sizeInBits="16" encoding="unsigned" byteOrder="leastSignificantByteFirst"/>
      </IntegerParameterType>
      <IntegerParameterType name="uptime_type" signed="false" sizeInBits="32">
        <IntegerDataEncoding sizeInBits="32" encoding="unsigned" byteOrder="leastSignificantByteFirst"/>
      </IntegerParameterType>
    </ParameterTypeSet>
    <ParameterSet>
      <Parameter name="telemetry-type" parameterTypeRef="telemetry-type">
        <ParameterProperties dataSource="telemetered" persistence="true"/>
      </Parameter>
      <Parameter name="uptime" parameterTypeRef="uptime_type">
        <ParameterProperties dataSource="telemetered" persistence="true"/>
      </Parameter>
      <Parameter name="uptime2" parameterTypeRef="uptime_type">
        <ParameterProperties dataSource="telemetered" persistence="true"/>
      </Parameter>
    </ParameterSet>
    <ContainerSet>
      <SequenceContainer name="HK" abstract="false">
        <EntryList>
          <ParameterRefEntry parameterRef="uptime">
            <LocationInContainerInBits referenceLocation="previousEntry">
              <FixedValue>0</FixedValue>
            </LocationInContainerInBits>
          </ParameterRefEntry>
        </EntryList>
        <BaseContainer containerRef="header">
          <RestrictionCriteria>
            <BooleanExpression>
              <Condition>
                <ParameterInstanceRef parameterRef="telemetry-type" useCalibratedValue="true"/>
                <ComparisonOperator>==</ComparisonOperator>
                <Value>0</Value>
              </Condition>
            </BooleanExpression>
          </RestrictionCriteria>
        </BaseContainer>
      </SequenceContainer>
      <SequenceContainer name="header" abstract="true">
        <EntryList>
          <ParameterRefEntry parameterRef="telemetry-type">
            <LocationInContainerInBits referenceLocation="previousEntry">
              <FixedValue>0</FixedValue>
            </LocationInContainerInBits>
          </ParameterRefEntry>
        </EntryList>
      </SequenceContainer>
    </ContainerSet>
  </TelemetryMetaData>
  <CommandMetaData/>
  <SpaceSystem name="sub">
    <TelemetryMetaData>
      <ContainerSet>
        <SequenceContainer name="Foo" abstract="false">
          <EntryList>
            <ParameterRefEntry parameterRef="../uptime2">
              <LocationInContainerInBits referenceLocation="previousEntry">
                <FixedValue>0</FixedValue>
              </LocationInContainerInBits>
            </ParameterRefEntry>
          </EntryList>
          <BaseContainer containerRef="../header">
            <RestrictionCriteria>
              <BooleanExpression>
                <Condition>
                  <ParameterInstanceRef parameterRef="../telemetry-type" useCalibratedValue="true"/>
                  <ComparisonOperator>==</ComparisonOperator>
                  <Value>1</Value>
                </Condition>
              </BooleanExpression>
            </RestrictionCriteria>
          </BaseContainer>
        </SequenceContainer>
      </ContainerSet>
    </TelemetryMetaData>
    <CommandMetaData/>
  </SpaceSystem>
</SpaceSystem>
```

**This is a script I came up with. But failed to genearte the above**

```python
from yamcs.pymdb import *
import sys

system = System("Spacecraft")
subsys = Subsystem(system, "sub")

base_container = Container(
    system=system,
    name="header",
    abstract=True,
    entries=[
        ParameterEntry(IntegerParameter(system=system, name="telemetry-type", signed=False, encoding=uint16le_t)),
    ],
)

hk_container = Container(
    system = system,
    name = "HK",
    base = base_container,
    entries = [
        ParameterEntry(IntegerParameter(system=system, name="uptime", signed=False, encoding=uint32le_t)),
    ],
    condition = eq("/Spacecraft/telemetry-type", 0),
)

foo_container = Container(
    system = subsys,
    name = "Foo",
    base = base_container,
    entries = [
        ParameterEntry(IntegerParameter(system=system, name="uptime2", signed=False, encoding=uint32le_t)),
    ],
    condition = eq("/Spacecraft/telemetry-type", 1),
)

with open("quickstart/src/main/yamcs/mdb/udp.xml", "wt") as f:
    system.dump(f)
```

**parameters.py**

https://github.com/yamcs/pymdb/blob/14a538aef689c56b0b7e499c2270a6bf39fcb091/src/yamcs/pymdb/parameters.py#L473-L520

I see that in `IntegerParameter()`, you call `IntegerDataType.__init__()` and `Parameter.__init__()`, so I thought I can call them instead of `ParameterEntry()` but 

```python
uptime1 = Parameter(system=system, name='uptime1')
```

This cases the following error because of this line in 
https://github.com/yamcs/pymdb/blob/14a538aef689c56b0b7e499c2270a6bf39fcb091/src/yamcs/pymdb/xtce.py#L626

```
❯ python3 ./gen.py
Traceback (most recent call last):
  File "/tmp/foo/./gen.py", line 41, in <module>
    system.dump(f)
  File "/tmp/foo/.venv/lib/python3.12/site-packages/yamcs/pymdb/systems.py", line 217, in dump
    xml = self.dumps(indent=indent, top_comment=top_comment)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/foo/.venv/lib/python3.12/site-packages/yamcs/pymdb/systems.py", line 224, in dumps
    return xtce.XTCE12Generator(self).to_xtce(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/foo/.venv/lib/python3.12/site-packages/yamcs/pymdb/xtce.py", line 149, in to_xtce
    el = self.generate_space_system(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/foo/.venv/lib/python3.12/site-packages/yamcs/pymdb/xtce.py", line 2096, in generate_space_system
    self.add_telemetry_metadata(el, system)
  File "/tmp/foo/.venv/lib/python3.12/site-packages/yamcs/pymdb/xtce.py", line 533, in add_telemetry_metadata
    self.add_parameter_type_set(el, system)
  File "/tmp/foo/.venv/lib/python3.12/site-packages/yamcs/pymdb/xtce.py", line 624, in add_parameter_type_set
    raise ExportError(f"Unexpected parameter type {parameter.__class__}")
yamcs.pymdb.exceptions.ExportError: Unexpected parameter type <class 'yamcs.pymdb.parameters.Parameter'>

Compilation exited abnormally with code 1 at Sat Jul 20 19:53:49
```

This if-else check to se `IntegerParameter` and other types with `isinstance()`. Thus, we have to call `IntegerParameter()` but I can't reuse the parameter type with it.

**Comment by fqqb** [comment]
"Parameter" and "Parameter Type" are merged in this library. The XTCE is generated, so you have limited influence in how the generated XTCE is structured. Each parameter has a one-to-one relation with a parameter type.

Rather I see the opportunity for reuse more at the level of the Python definition (methods, variables, ...), at the expense of maybe somewhat larger XML (and perhaps less readable).

What is the value to you for reusing types? From a Yamcs point of view, I don't see this making much of a difference (?)

**Comment by yashi** [comment]
It's just that for someone who knows XTCE, it feels odd to see them merged.

If the current form is the design choise, that's fine by me. But because it uses Python, I feel that it can give users a choice how they want to write.

```py
t = ParameterType(...)
p1 = Parameter(system=system, name="name1", type=t)
p2 = Parameter(system=system, name="name2", type=t)
```

```py
type = get_my_type()
p1 = IntegerParameter(system=system, name="name1", **type)
p2 = IntegerParameter(system=system, name="name2", **type)
```

The former can perfectly be valid as the latter. Plus, because the former holds the reference to the type, you can generate a simpler XML.

I agree that IntegerParameter() is useful in many instances due to its simplicity. However, considering the increasing number of telemetry parameters in spacecraft, especially in constellations, it would be beneficial to avoid duplicating types at the XML level, IMHO.

Anyway, thanks for your comment.
